run:
  timeout: 5m

linters-settings:
  cyclop:
    max-complexity: 30

  errcheck:
    check-type-assertions: true

  funlen:
    lines: 150
    statements: 70

  gocritic:
    settings:
      captLocal:
        paramsOnly: false
      underef:
        skipRecvDeref: false

  govet:
    enable-all: true
    disable:
      - fieldalignment
    settings:
      shadow:
        strict: true

  nolintlint:
    allow-no-explanation: [funlen, gocognit, cyclop, gocyclo, lll]
    require-explanation: true
    require-specific: true

  lll:
    line-length: 140

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - asasalint
    - bidichk
    - bodyclose
    - cyclop
    - durationcheck
    - exportloopref
    - funlen
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - lll
    - nilerr
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - reassign
    - tparallel
    - unconvert
    - whitespace

issues:
  exclude-rules:
    - source: "^//\\s*go:generate\\s"
      linters: [lll]
    - path: "_test\\.go"
      linters:
        - bodyclose
        - funlen
        - gosec
        - noctx
