// Code generated by generate_categories.go; DO NOT EDIT.
package hopgo

//go:generate go run generate_categories.go

// ProjectTokens is an auto-generated struct which is used to allow for simple categorisation of the APIs.
// It is public since it may be desired to store a reference to this somewhere, however, do NOT create a instance of this
// directly. Instead, call NewClient and then go to the field Projects.ProjectTokens.
type ProjectTokens struct {
	c *Client
}

// ProjectsSecrets is an auto-generated struct which is used to allow for simple categorisation of the APIs.
// It is public since it may be desired to store a reference to this somewhere, however, do NOT create a instance of this
// directly. Instead, call NewClient and then go to the field Projects.Secrets.
type ProjectsSecrets struct {
	c *Client
}

// Projects is an auto-generated struct which is used to allow for simple categorisation of the APIs.
// It is public since it may be desired to store a reference to this somewhere, however, do NOT create a instance of this
// directly. Instead, call NewClient and then go to the field Projects.
type Projects struct {
	c *Client

	ProjectTokens *ProjectTokens
	Secrets       *ProjectsSecrets
}

func newProjects(c *Client) *Projects {
	return &Projects{
		c:             c,
		ProjectTokens: &ProjectTokens{c},
		Secrets:       &ProjectsSecrets{c},
	}
}
