package hop

// Code generated by generate_categories.go; DO NOT EDIT.

//go:generate go run generate_categories.go

// ClientCategoryChannelsTokens is an auto-generated struct which is used to allow for simple categorisation of the APIs.
// It is public since it may be desired to store a reference to this somewhere, however, do NOT create a instance of this
// directly. Instead, call NewClient and then go to the field Channels.Tokens.
type ClientCategoryChannelsTokens struct {
	c *Client
}

// ClientCategoryChannels is an auto-generated struct which is used to allow for simple categorisation of the APIs.
// It is public since it may be desired to store a reference to this somewhere, however, do NOT create a instance of this
// directly. Instead, call NewClient and then go to the field Channels.
type ClientCategoryChannels struct {
	c *Client

	Tokens *ClientCategoryChannelsTokens
}

func newChannels(c *Client) *ClientCategoryChannels {
	return &ClientCategoryChannels{
		c:      c,
		Tokens: &ClientCategoryChannelsTokens{c},
	}
}

// ClientCategoryIgniteGateways is an auto-generated struct which is used to allow for simple categorisation of the APIs.
// It is public since it may be desired to store a reference to this somewhere, however, do NOT create a instance of this
// directly. Instead, call NewClient and then go to the field Ignite.Gateways.
type ClientCategoryIgniteGateways struct {
	c *Client
}

// ClientCategoryIgniteDeployments is an auto-generated struct which is used to allow for simple categorisation of the APIs.
// It is public since it may be desired to store a reference to this somewhere, however, do NOT create a instance of this
// directly. Instead, call NewClient and then go to the field Ignite.Deployments.
type ClientCategoryIgniteDeployments struct {
	c *Client
}

// ClientCategoryIgniteContainers is an auto-generated struct which is used to allow for simple categorisation of the APIs.
// It is public since it may be desired to store a reference to this somewhere, however, do NOT create a instance of this
// directly. Instead, call NewClient and then go to the field Ignite.Containers.
type ClientCategoryIgniteContainers struct {
	c *Client
}

// ClientCategoryIgnite is an auto-generated struct which is used to allow for simple categorisation of the APIs.
// It is public since it may be desired to store a reference to this somewhere, however, do NOT create a instance of this
// directly. Instead, call NewClient and then go to the field Ignite.
type ClientCategoryIgnite struct {
	c *Client

	Gateways    *ClientCategoryIgniteGateways
	Deployments *ClientCategoryIgniteDeployments
	Containers  *ClientCategoryIgniteContainers
}

func newIgnite(c *Client) *ClientCategoryIgnite {
	return &ClientCategoryIgnite{
		c:           c,
		Gateways:    &ClientCategoryIgniteGateways{c},
		Deployments: &ClientCategoryIgniteDeployments{c},
		Containers:  &ClientCategoryIgniteContainers{c},
	}
}

// ClientCategoryPipeRooms is an auto-generated struct which is used to allow for simple categorisation of the APIs.
// It is public since it may be desired to store a reference to this somewhere, however, do NOT create a instance of this
// directly. Instead, call NewClient and then go to the field Pipe.Rooms.
type ClientCategoryPipeRooms struct {
	c *Client
}

// ClientCategoryPipe is an auto-generated struct which is used to allow for simple categorisation of the APIs.
// It is public since it may be desired to store a reference to this somewhere, however, do NOT create a instance of this
// directly. Instead, call NewClient and then go to the field Pipe.
type ClientCategoryPipe struct {
	c *Client

	Rooms *ClientCategoryPipeRooms
}

func newPipe(c *Client) *ClientCategoryPipe {
	return &ClientCategoryPipe{
		c:     c,
		Rooms: &ClientCategoryPipeRooms{c},
	}
}

// ClientCategoryProjectsTokens is an auto-generated struct which is used to allow for simple categorisation of the APIs.
// It is public since it may be desired to store a reference to this somewhere, however, do NOT create a instance of this
// directly. Instead, call NewClient and then go to the field Projects.Tokens.
type ClientCategoryProjectsTokens struct {
	c *Client
}

// ClientCategoryProjectsSecrets is an auto-generated struct which is used to allow for simple categorisation of the APIs.
// It is public since it may be desired to store a reference to this somewhere, however, do NOT create a instance of this
// directly. Instead, call NewClient and then go to the field Projects.Secrets.
type ClientCategoryProjectsSecrets struct {
	c *Client
}

// ClientCategoryProjects is an auto-generated struct which is used to allow for simple categorisation of the APIs.
// It is public since it may be desired to store a reference to this somewhere, however, do NOT create a instance of this
// directly. Instead, call NewClient and then go to the field Projects.
type ClientCategoryProjects struct {
	c *Client

	Tokens  *ClientCategoryProjectsTokens
	Secrets *ClientCategoryProjectsSecrets
}

func newProjects(c *Client) *ClientCategoryProjects {
	return &ClientCategoryProjects{
		c:       c,
		Tokens:  &ClientCategoryProjectsTokens{c},
		Secrets: &ClientCategoryProjectsSecrets{c},
	}
}

// ClientCategoryRegistryImages is an auto-generated struct which is used to allow for simple categorisation of the APIs.
// It is public since it may be desired to store a reference to this somewhere, however, do NOT create a instance of this
// directly. Instead, call NewClient and then go to the field Registry.Images.
type ClientCategoryRegistryImages struct {
	c *Client
}

// ClientCategoryRegistry is an auto-generated struct which is used to allow for simple categorisation of the APIs.
// It is public since it may be desired to store a reference to this somewhere, however, do NOT create a instance of this
// directly. Instead, call NewClient and then go to the field Registry.
type ClientCategoryRegistry struct {
	c *Client

	Images *ClientCategoryRegistryImages
}

func newRegistry(c *Client) *ClientCategoryRegistry {
	return &ClientCategoryRegistry{
		c:      c,
		Images: &ClientCategoryRegistryImages{c},
	}
}

// ClientCategoryUsersMe is an auto-generated struct which is used to allow for simple categorisation of the APIs.
// It is public since it may be desired to store a reference to this somewhere, however, do NOT create a instance of this
// directly. Instead, call NewClient and then go to the field Users.Me.
type ClientCategoryUsersMe struct {
	c *Client
}

// ClientCategoryUsers is an auto-generated struct which is used to allow for simple categorisation of the APIs.
// It is public since it may be desired to store a reference to this somewhere, however, do NOT create a instance of this
// directly. Instead, call NewClient and then go to the field Users.
type ClientCategoryUsers struct {
	c *Client

	Me *ClientCategoryUsersMe
}

func newUsers(c *Client) *ClientCategoryUsers {
	return &ClientCategoryUsers{
		c:  c,
		Me: &ClientCategoryUsersMe{c},
	}
}
