package types

// Code generated by generate_stringer.go; DO NOT EDIT.

//go:generate go run generate_stringer.go

// String returns the string representation of this value. This function is auto-generated.
func (x LeapUnavailableEvent) String() string {
	return stringifyValue(x)
}

// String returns the string representation of this value. This function is auto-generated.
func (x LeapAvailableEvent) String() string {
	return stringifyValue(x)
}

// String returns the string representation of this value. This function is auto-generated.
func (x LeapChannelStateUpdateEvent) String() string {
	return stringifyValue(x)
}
