package types

// Code generated by generate_stringer.go; DO NOT EDIT.

//go:generate go run generate_stringer.go

// String returns the string representation of this value. This function is auto-generated.
func (x LeapUnavailableEvent) String() string {
	return stringifyValue(x)
}

// String returns the string representation of this value. This function is auto-generated.
func (x LeapAvailableEvent) String() string {
	return stringifyValue(x)
}

// String returns the string representation of this value. This function is auto-generated.
func (x LeapChannelStateUpdateEvent) String() string {
	return stringifyValue(x)
}

// String returns the string representation of this value. This function is auto-generated.
func (x LeapPipeRoomAvailableEvent) String() string {
	return stringifyValue(x)
}

// String returns the string representation of this value. This function is auto-generated.
func (x LeapPipeRoomUpdateEvent) String() string {
	return stringifyValue(x)
}

// String returns the string representation of this value. This function is auto-generated.
func (x IgniteDeploymentPatchOpts) String() string {
	return stringifyValue(x)
}

// String returns the string representation of this value. This function is auto-generated.
func (x Container) String() string {
	return stringifyValue(x)
}

// String returns the string representation of this value. This function is auto-generated.
func (x ContainerMetadata) String() string {
	return stringifyValue(x)
}

// String returns the string representation of this value. This function is auto-generated.
func (x DeploymentConfig) String() string {
	return stringifyValue(x)
}

// String returns the string representation of this value. This function is auto-generated.
func (x DeploymentConfigPartial) String() string {
	return stringifyValue(x)
}

// String returns the string representation of this value. This function is auto-generated.
func (x VolumeDefinition) String() string {
	return stringifyValue(x)
}

// String returns the string representation of this value. This function is auto-generated.
func (x VolumeFormat) String() string {
	return stringifyValue(x)
}
